[package]
name = "diffiehellman-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
colored = "2.1"
eframe = "0.27.2"
egui = "0.27.2"
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"
[[bin]]
name = "console"
path = "src/main.rs"

[[bin]]
name = "interface"
path = "src/main_int.rs"
